[loggers]
keys=root, gunicorn.error, gunicorn.access

[handlers]
keys=default, flask

[formatters]
keys=verbose, basic

[logger_root]
level=WARNING
handlers=default

[logger_gunicorn.error]
level=WARNING
handlers=flask
propagate=1
qualname=gunicorn.error

[logger_gunicorn.access]
level=WARNING
handlers=flask
propagate=0
qualname=gunicorn.access

[handler_default]
class=logging.handlers.RotatingFileHandler
formatter=verbose
args=("logs/app.log", "a", 5242880, 4, "utf-8")

[handler_flask]
class=logging.handlers.RotatingFileHandler
formatter=basic
args=("logs/app.log", "a", 5242880, 4, "utf-8")

[formatter_verbose]
format=%(asctime)s [%(process)d] [%(levelname)s] %(message)s
datefmt=%Y-%m-%d %H:%M:%S
class=logging.Formatter

[formatter_basic]
format=%(message)s
class=logging.Formatter
